# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=128)),
                ('ShortInfo', models.TextField()),
                ('Wiki_Link', models.TextField()),
                ('MainPictureSource', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=128)),
                ('ShortInfo', models.TextField()),
                ('AdvancedInfo', models.TextField()),
                ('MainPictureSource', models.TextField()),
                ('AnyImagesSource', models.TextField()),
                ('AudioGuideSource', models.TextField()),
                ('Latitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
                ('xCoord_OnBuildMap', models.IntegerField()),
                ('yCoord_OnBuildMap', models.IntegerField()),
                ('BuildingMapSource', models.TextField()),
                ('Artists', models.TextField()),
                ('Model3D', models.TextField()),
                ('BuildMapZone', models.TextField()),
                ('Category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=128)),
                ('ShortInfo', models.TextField()),
                ('AdvancedInfo', models.TextField()),
                ('MainPictureSource', models.TextField()),
                ('Route', models.TextField()),
            ],
        ),
    ]
