# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
        migrations.RenameModel(
            old_name='Tours',
            new_name='Tour',
        ),
    ]
