# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0002_auto_20160429_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='MainPictureSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='ShortInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Wiki_Link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='AdvancedInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='AnyImagesSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='Artists',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='AudioGuideSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='BuildMapZone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='BuildingMapSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='Category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='Latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='Longtitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='MainPictureSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='Model3D',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='ShortInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='xCoord_OnBuildMap',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='yCoord_OnBuildMap',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='AdvancedInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='MainPictureSource',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Route',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ShortInfo',
            field=models.TextField(blank=True),
        ),
    ]
