# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0005_auto_20160429_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='Artists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourmeApp.Artist'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='AttractionRoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourmeApp.Attraction'),
        ),
    ]
