# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:50
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0009_auto_20160430_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='Longtitude',
        ),
        migrations.AddField(
            model_name='attraction',
            name='MapCoordinates',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
