# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0010_auto_20160430_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Attraction')),
            ],
        ),
        migrations.AlterField(
            model_name='attraction',
            name='MapCoordinates',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
        migrations.AddField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourmeApp.Attraction'),
        ),
    ]
