# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0011_auto_20160430_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('Title',), 'verbose_name': '\u0410\u0432\u0442\u043e\u0440', 'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ('Title',), 'verbose_name': '\u0414\u043e\u0441\u0442\u043e\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u0414\u043e\u0441\u0442\u043e\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('Title',), 'verbose_name': '\u0422\u0443\u0440', 'verbose_name_plural': '\u0422\u0443\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to='\u041f\u0430\u043c\u044f\u0442\u043d\u0438\u043a \u041b\u0435\u043d\u0438\u043d\u0443'),
        ),
    ]
