# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0012_auto_20160430_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to='\u041f\u0430\u043c\u044f\u0442\u043d\u0438\u043a \u0421\u0432\u0435\u0440\u0434\u043b\u043e\u0432\u0443'),
        ),
    ]
