# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0013_auto_20160430_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
