# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tourmeApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmeApp', '0039_auto_20160801_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 10, 8, 42, 1, 542709, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 10, 8, 42, 27, 271252, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractionimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0444\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='tour',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 10, 8, 43, 5, 695613, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='MainPictureSource',
            field=models.ImageField(blank=True, upload_to=tourmeApp.models.upload_mainimage_path_handler, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0430\u0432\u0442\u043e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='MainPictureSource',
            field=models.ImageField(blank=True, upload_to=tourmeApp.models.upload_mainimage_path_handler, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0444\u043e\u0442\u043e'),
        ),
    ]
